// This is the single place to edit the homepage map. Questions are the anchors;
// the image fragments are intentionally small evidence of each area, not a gallery.
export const worldNodes = [
  {
    id: "research",
    label: "What am I trying to understand?",
    eyebrow: "Brains, birth, bodies",
    summary: "Questions about AI, health, public health, and the systems that shape care.",
    href: "/research/",
    x: 705,
    y: 245,
    stage: 0.2,
    kind: "question",
  },
  {
    id: "achievements",
    label: "How do I contribute?",
    eyebrow: "Milestones and service",
    summary: "Selected work, leadership, and the experiences that have shaped this path.",
    href: "/achievements/",
    x: 1110,
    y: 355,
    stage: 0.34,
    kind: "question",
  },
  {
    id: "art",
    label: "What do I make?",
    eyebrow: "Making meaning",
    summary: "A visual practice alongside research: images, experiments, and ways of seeing.",
    href: "/art/",
    x: 900,
    y: 720,
    stage: 0.47,
    kind: "question",
  },
  {
    id: "thoughts",
    label: "What am I thinking through?",
    eyebrow: "Learning in public",
    summary: "Writing about ideas, questions, and the work of becoming.",
    href: "/blog/",
    x: 380,
    y: 705,
    stage: 0.6,
    kind: "question",
  },
  {
    id: "mirror",
    label: "What reflects me back?",
    eyebrow: "What people say",
    summary: "A record of the people, collaborations, and reflections around this work.",
    href: "/mirror/",
    x: 250,
    y: 420,
    stage: 0.73,
    kind: "question",
  },
]

// x/y below are a seed, not a final coordinate: app.js reads each satellite's direction and
// rough distance from its parent hub, then computes the actual resting position itself (pushed
// out just far enough to clear the hub's label and every other satellite, never closer). Edit
// these to nudge which side of the hub a satellite prefers and roughly how far out it starts.
export const worldSatellites = [
  {
    id: "research-portrait",
    parentId: "research",
    label: "Research in practice",
    eyebrow: "Research",
    summary: "Work across health, AI, and the systems that shape care.",
    href: "/research/",
    x: 520,
    y: 105,
    stage: 0.24,
    image: "/images/profile.jpg",
    size: "small",
  },
  {
    id: "research-forest",
    parentId: "research",
    label: "Questions of care",
    eyebrow: "Research",
    summary: "A practice grounded in curiosity, evidence, and people.",
    href: "/research/",
    x: 845,
    y: 105,
    stage: 0.27,
    image: "/images/map/about3.jpg",
    fullImage: "/images/about3.jpeg",
    size: "medium",
  },
  {
    id: "achievement-quiet",
    parentId: "achievements",
    label: "Service and leadership",
    eyebrow: "Achievements",
    summary: "Selected milestones, responsibilities, and collaborations.",
    href: "/achievements/",
    x: 1185,
    y: 190,
    stage: 0.38,
    image: "/images/map/about4.jpg",
    fullImage: "/images/about4.jpg",
    size: "small",
  },
  {
    id: "achievement-landscape",
    parentId: "achievements",
    label: "A life in progress",
    eyebrow: "Achievements",
    summary: "The longer arc behind the formal record.",
    href: "/achievements/",
    x: 1300,
    y: 465,
    stage: 0.41,
    image: "/images/map/home.jpg",
    fullImage: "/images/art_photos/home.jpg",
    size: "medium",
  },
  {
    id: "art-blue",
    parentId: "art",
    label: "Colour study",
    eyebrow: "Art",
    summary: "A visual practice of attention, play, and experimentation.",
    href: "/art/",
    x: 1115,
    y: 600,
    stage: 0.51,
    image: "/images/map/color-study.jpg",
    fullImage: "/images/art_photos/color_study.jpg",
    size: "medium",
  },
  {
    id: "Portrait of Ashley Alexander",
    parentId: "art",
    label: "portrait",
    eyebrow: "Art",
    summary: "Creatively inspired by those I look up to.",
    href: "/art/",
    x: 1015,
    y: 875,
    stage: 0.54,
    image: "/images/map/ashley-alexander-portrait.jpg",
    fullImage: "/images/art_photos/ashley-alexander-portrait.jpg",
    size: "small",
  },
  {
    id: "little rodent",
    parentId: "art",
    label: "Runner",
    eyebrow: "Art",
    summary: "A cute, little friend says hi :)",
    href: "/art/",
    x: 1245,
    y: 775,
    stage: 0.56,
    image: "/images/map/little-rodent.jpg",
    fullImage: "/images/art_photos/little-rodent.jpg",
    size: "small",
    mobileHidden: true,
  },
  {
    id: "thoughts-note",
    parentId: "thoughts",
    label: "Writing in public",
    eyebrow: "Thoughts",
    summary: "Notes on ideas, questions, and becoming.",
    href: "/blog/",
    x: 145,
    y: 820,
    stage: 0.64,
    image: "/images/map/about5.jpg",
    fullImage: "/images/about5.png",
    size: "medium",
  },
  {
    id: "thoughts-dream",
    parentId: "thoughts",
    label: "A way of seeing",
    eyebrow: "Thoughts",
    summary: "Small reflections that lead to longer writing.",
    href: "/blog/",
    x: 500,
    y: 875,
    stage: 0.67,
    image: "/images/map/about1.jpg",
    fullImage: "/images/about1.jpg",
    size: "small",
  },
  {
    id: "mirror-home",
    parentId: "mirror",
    label: "People and reflection",
    eyebrow: "Mirror",
    summary: "A record of voices, encounters, and shared work.",
    href: "/mirror/",
    x: 85,
    y: 285,
    stage: 0.76,
    image: "/images/map/achievement-landscape.jpg",
    fullImage: "/images/PXL_20251009_161419927~4.jpg",
    size: "small",
  },
  {
    id: "mirror-portrait",
    parentId: "mirror",
    label: "What stays with us",
    eyebrow: "Mirror",
    summary: "The people and reflections that shape a life.",
    href: "/mirror/",
    x: 125,
    y: 590,
    stage: 0.79,
    image: "/images/map/about2.jpg",
    fullImage: "/images/about2.jpg",
    size: "medium",
  },
  {
    id: "video-emotions-two",
    parentId: "research",
    label: "Emotions 2",
    eyebrow: "Film",
    summary: "A video study previously featured with the research work.",
    href: "https://www.youtube.com/watch?v=BJNtmcr7ipw",
    linkLabel: "Watch on YouTube",
    external: true,
    video: true,
    x: 970,
    y: 260,
    stage: 0.3,
    image: "https://i.ytimg.com/vi/BJNtmcr7ipw/hqdefault.jpg",
    size: "medium",
  },
  {
    id: "video-emotions-one",
    parentId: "art",
    label: "Emotions 1",
    eyebrow: "Film",
    summary: "A video study previously featured in the portfolio.",
    href: "https://www.youtube.com/watch?v=M-jP8FXD_lQ",
    linkLabel: "Watch on YouTube",
    external: true,
    video: true,
    x: 720,
    y: 590,
    stage: 0.57,
    image: "https://i.ytimg.com/vi/M-jP8FXD_lQ/hqdefault.jpg",
    size: "medium",
  },
  {
    id: "video-letter-future-selves",
    parentId: "thoughts",
    label: "A Letter to Our Future Selves",
    eyebrow: "Film",
    summary: "A video letter previously featured in the portfolio.",
    href: "https://www.youtube.com/watch?v=zX2OgG-7TLA",
    linkLabel: "Watch on YouTube",
    external: true,
    video: true,
    x: 615,
    y: 705,
    stage: 0.7,
    image: "https://i.ytimg.com/vi/zX2OgG-7TLA/hqdefault.jpg",
    size: "medium",
  },
]

// Every satellite gets a line back to its parent hub, so the map reads as one connected graph
// rather than a curated few. Lines draw in shortly after their satellite has faded in.
const LINE_STAGE_OFFSET = 0.015
export const worldConnections = worldSatellites.map((satellite) => ({
  from: satellite.parentId,
  to: satellite.id,
  stage: Math.min(1, satellite.stage + LINE_STAGE_OFFSET),
}))

// The camera begins close to the centre and gradually lets the whole world in.
export const cameraKeyframes = [
  { at: 0, x: 720, y: 480, scale: 1.42 },
  { at: 0.22, x: 720, y: 445, scale: 1.13 },
  { at: 0.56, x: 720, y: 475, scale: 0.88 },
  { at: 1, x: 720, y: 490, scale: 0.7 },
]
