// This is the single place to edit the homepage map. Questions are the anchors;
// the image fragments are intentionally small evidence of each area, not a gallery.
export const worldNodes = [
  {
    id: "research",
    label: "What am I trying to understand?",
    eyebrow: "Brains, birth, bodies",
    summary: "Questions about AI, health, public health, and the systems that shape care.",
    href: "/research/",
    x: 730,
    y: 205,
    stage: 0.2,
    kind: "question",
  },
  {
    id: "achievements",
    label: "How do I contribute?",
    eyebrow: "Milestones and service",
    summary: "Selected work, leadership, and the experiences that have shaped this path.",
    href: "/achievements/",
    x: 1115,
    y: 330,
    stage: 0.34,
    kind: "question",
  },
  {
    id: "art",
    label: "What do I make?",
    eyebrow: "Making meaning",
    summary: "A visual practice alongside research: images, experiments, and ways of seeing.",
    href: "/art/",
    x: 1090,
    y: 700,
    stage: 0.47,
    kind: "question",
  },
  {
    id: "thoughts",
    label: "What am I thinking through?",
    eyebrow: "Learning in public",
    summary: "Writing about ideas, questions, and the work of becoming.",
    href: "/blog/",
    x: 370,
    y: 700,
    stage: 0.6,
    kind: "question",
  },
  {
    id: "mirror",
    label: "What reflects me back?",
    eyebrow: "What people say",
    summary: "A record of the people, collaborations, and reflections around this work.",
    href: "/mirror/",
    x: 315,
    y: 340,
    stage: 0.73,
    kind: "question",
  },
  {
    id: "cv",
    label: "CV",
    eyebrow: "The longer record",
    summary: "Education, experience, publications, and the formal shape of a life in progress.",
    href: "/cv/",
    x: 1040,
    y: 890,
    stage: 0.84,
    kind: "utility",
  },
  {
    id: "trackers",
    label: "What am I practising?",
    eyebrow: "Habit trackers",
    summary: "A living record of the practices I return to, one day at a time.",
    href: "/tracked-habits/",
    x: 640,
    y: 880,
    stage: 0.84,
    kind: "tracker",
    tracker: true,
  },
]

export const worldSatellites = [
  {
    id: "research-portrait",
    parentId: "research",
    label: "Research in practice",
    eyebrow: "Research",
    summary: "Work across health, AI, and the systems that shape care.",
    href: "/research/",
    x: 530,
    y: 130,
    stage: 0.24,
    image: "/images/profile.jpg",
    size: "small",
  },
  {
    id: "research-forest",
    parentId: "research",
    label: "Questions of care",
    eyebrow: "Research",
    summary: "A practice grounded in curiosity, evidence, and people.",
    href: "/research/",
    x: 920,
    y: 138,
    stage: 0.27,
    image: "/images/about2.jpg",
    size: "medium",
  },
  {
    id: "achievement-quiet",
    parentId: "achievements",
    label: "Service and leadership",
    eyebrow: "Achievements",
    summary: "Selected milestones, responsibilities, and collaborations.",
    href: "/achievements/",
    x: 1210,
    y: 220,
    stage: 0.38,
    image: "/images/about4.jpg",
    size: "small",
  },
  {
    id: "achievement-landscape",
    parentId: "achievements",
    label: "A life in progress",
    eyebrow: "Achievements",
    summary: "The longer arc behind the formal record.",
    href: "/achievements/",
    x: 1265,
    y: 458,
    stage: 0.41,
    image: "/images/PXL_20251009_161419927~4.jpg",
    size: "medium",
  },
  {
    id: "art-blue",
    parentId: "art",
    label: "Colour study",
    eyebrow: "Art",
    summary: "A visual practice of attention, play, and experimentation.",
    href: "/art/",
    x: 1215,
    y: 785,
    stage: 0.51,
    image: "/images/art_photos/color_study.jpg",
    size: "medium",
  },
  {
    id: "art-water",
    parentId: "art",
    label: "Diving swimmer",
    eyebrow: "Art",
    summary: "Images made beside the research work.",
    href: "/art/",
    x: 965,
    y: 845,
    stage: 0.54,
    image: "/images/art_photos/uvm-diving-swimmer.jpg",
    size: "small",
  },
  {
    id: "art-runner",
    parentId: "art",
    label: "Runner",
    eyebrow: "Art",
    summary: "Fragments from the art portfolio.",
    href: "/art/",
    x: 1330,
    y: 705,
    stage: 0.56,
    image: "/images/art_photos/runner.jpg",
    size: "small",
    mobileHidden: true,
  },
  {
    id: "thoughts-note",
    parentId: "thoughts",
    label: "Writing in public",
    eyebrow: "Thoughts",
    summary: "Notes on ideas, questions, and becoming.",
    href: "/blog/",
    x: 178,
    y: 800,
    stage: 0.64,
    image: "/images/about5.png",
    size: "medium",
  },
  {
    id: "thoughts-dream",
    parentId: "thoughts",
    label: "A way of seeing",
    eyebrow: "Thoughts",
    summary: "Small reflections that lead to longer writing.",
    href: "/blog/",
    x: 420,
    y: 850,
    stage: 0.67,
    image: "/images/art_photos/dream.jpg",
    size: "small",
  },
  {
    id: "mirror-home",
    parentId: "mirror",
    label: "People and reflection",
    eyebrow: "Mirror",
    summary: "A record of voices, encounters, and shared work.",
    href: "/mirror/",
    x: 150,
    y: 225,
    stage: 0.76,
    image: "/images/art_photos/home.jpg",
    size: "small",
  },
  {
    id: "mirror-portrait",
    parentId: "mirror",
    label: "What stays with us",
    eyebrow: "Mirror",
    summary: "The people and reflections that shape a life.",
    href: "/mirror/",
    x: 115,
    y: 495,
    stage: 0.79,
    image: "/images/about3.jpeg",
    size: "medium",
  },
  {
    id: "video-emotions-two",
    parentId: "research",
    label: "Emotions 2",
    eyebrow: "Film",
    summary: "A video study previously featured with the research work.",
    href: "https://www.youtube.com/watch?v=BJNtmcr7ipw",
    linkLabel: "Watch on YouTube",
    external: true,
    video: true,
    x: 1015,
    y: 96,
    stage: 0.3,
    image: "https://i.ytimg.com/vi/BJNtmcr7ipw/hqdefault.jpg",
    size: "medium",
  },
  {
    id: "video-emotions-one",
    parentId: "art",
    label: "Emotions 1",
    eyebrow: "Film",
    summary: "A video study previously featured in the portfolio.",
    href: "https://www.youtube.com/watch?v=M-jP8FXD_lQ",
    linkLabel: "Watch on YouTube",
    external: true,
    video: true,
    x: 1280,
    y: 600,
    stage: 0.57,
    image: "https://i.ytimg.com/vi/M-jP8FXD_lQ/hqdefault.jpg",
    size: "medium",
  },
  {
    id: "video-letter-future-selves",
    parentId: "thoughts",
    label: "A Letter to Our Future Selves",
    eyebrow: "Film",
    summary: "A video letter previously featured in the portfolio.",
    href: "https://www.youtube.com/watch?v=zX2OgG-7TLA",
    linkLabel: "Watch on YouTube",
    external: true,
    video: true,
    x: 210,
    y: 910,
    stage: 0.7,
    image: "https://i.ytimg.com/vi/zX2OgG-7TLA/hqdefault.jpg",
    size: "medium",
  },
]

export const worldConnections = [
  { from: "research", to: "research-portrait", stage: 0.25 },
  { from: "research", to: "video-emotions-two", stage: 0.3 },
  { from: "achievements", to: "achievement-quiet", stage: 0.39 },
  { from: "art", to: "art-blue", stage: 0.52 },
  { from: "art", to: "video-emotions-one", stage: 0.57 },
  { from: "thoughts", to: "thoughts-note", stage: 0.65 },
  { from: "thoughts", to: "video-letter-future-selves", stage: 0.7 },
  { from: "mirror", to: "mirror-home", stage: 0.77 },
]

// The camera begins close to the centre and gradually lets the whole world in.
export const cameraKeyframes = [
  { at: 0, x: 720, y: 480, scale: 1.42 },
  { at: 0.22, x: 720, y: 445, scale: 1.13 },
  { at: 0.56, x: 720, y: 475, scale: 0.88 },
  { at: 1, x: 720, y: 490, scale: 0.7 },
]
